# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0466b4ef05816e3b4c9fa3d88c792f42109c645c73dc4708ca084d892b4911938a6f655fa2813be956ee85aa96d76ab330427e652b2f1993dd5855eb242e6281

test:
  secret_key_base: f85ddac820b2f53a954b0eba5f22aedc09293f518c1dfd653c92a2cc0af1561303df7328e0eaec7d75db7a7f7b95e9fe2561f56bca6ad0f6494d6bdc783166bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
